package insurance.dto.enums;

public enum InsuranceReturnCode {
	OK, 
	MODEL_EXISTS, NO_MODEL,
	NO_VEHICLE, VEHICLE_EXISTS, 
	NO_PERSON, PERSON_EXISTS,
	NO_EMPLOYEE, EMPLOYEE_EXISTS,
	NO_AGENT, AGENT_EXISTS, 
	NO_LEGALENTITY, LEGALENTITY_EXISTS,
	NO_POLICY, PERSON_POLICY, 
	
	RETURN_DATE_WRONG, 

}
